// 14 communities, Springfield to the summit. Facts kept to well-established,
// verifiable local knowledge — no invented stats, prices, or school claims.
// Each area renders 5 pages: hub, buying-in, selling-in, living-in, faq.

export const AREAS = [
  {
    slug: 'springfield',
    name: 'Springfield',
    kicker: 'The city end of the corridor',
    img: '/assets/img/eugene-aerial-1.jpg',
    imgAlt: 'Aerial view over Springfield and Eugene, Oregon',
    blurb: 'Springfield is where the McKenzie corridor meets city services — the trailhead of Highway 126, minutes from the river and home to everything you drive down for.',
    hub: [
      `Springfield sits at the mouth of the McKenzie Valley, where the river country begins. It is the working heart of the corridor: the grocery runs, the hardware stores, the hospital, and the Highway 126 on-ramp that everyone up river uses. If your life splits between town convenience and river weekends, Springfield is the balance point.`,
      `The city has its own river story, too. The Middle Fork of the Willamette wraps its south side — Clearwater Park puts a boat launch and riverside trails inside city limits — and downtown Main Street has been steadily finding its stride with local shops and restaurants. PeaceHealth RiverBend anchors the Gateway area, which matters both for jobs and for anyone who wants to live rural without being far from care.`,
      `For buyers, Springfield offers the widest range on the corridor: established in-town neighborhoods, newer construction toward Thurston, and the first rural properties as you head east. For sellers, it is the deepest buyer pool in the area — homes here reach commuters, first-time buyers, and downsizers coming off acreage all at once.`,
    ],
    facts: [
      'Gateway to the McKenzie corridor via Highway 126',
      'Middle Fork Willamette riverfront at Clearwater Park',
      'PeaceHealth RiverBend medical center in the Gateway district',
      'Revitalized Main Street and downtown core',
      'The last full-service stop before the valley: groceries, fuel, trades',
    ],
    buying: [
      `Buying in Springfield means choosing between distinct pockets rather than one market. In-town neighborhoods offer sidewalks, city utilities, and shorter commutes. East toward Thurston you pick up newer construction and quick access to the river road. And on the eastern edge, the first acreage properties appear — often on well and septic even though town is five minutes away.`,
      `That mix is exactly why local guidance matters here: two homes a mile apart can live on completely different systems. I flag which side of the city-services line a property sits on before we ever tour it, so financing, inspections, and monthly costs never surprise you.`,
    ],
    selling: [
      `Springfield sellers have the corridor's biggest audience. Your buyer might be a first-timer priced out of Eugene, a hospital employee wanting a short commute, or an up-river owner trading acreage for convenience. Marketing that speaks to all three is how you create competition for your home.`,
      `Presentation still decides the price. Springfield buyers compare your home directly against Eugene alternatives, so honest pricing, sharp photos, and a clean pre-listing story keep you on the right side of that comparison.`,
    ],
    living: [
      `Living in Springfield is the both/and option: Saturday on the McKenzie, Sunday errands without a drive. The town has kept its unpretentious, hard-working character while the food and shopping have quietly improved, and the river paths mean you can be on a trail minutes after work.`,
      `Commutes are short by any standard — Eugene is across the river, and Highway 126 puts Walterville and Leaburg within an easy drive for river days. If you work anywhere in the metro and dream up river, Springfield is where many people start.`,
    ],
    faqs: [
      { q: 'Is Springfield a good base for exploring the McKenzie Valley?', a: 'Yes — Springfield sits at the start of Highway 126, the river road. Walterville is about ten minutes east, Leaburg and Vida roughly twenty to thirty, and the upper valley around Blue River and McKenzie Bridge is about an hour. It is the closest full-service city to the whole corridor.' },
      { q: 'Do Springfield homes use city utilities or wells and septic?', a: 'Most in-town homes are on city water and sewer, but properties on the eastern and southern edges can be on wells and septic systems. Always verify the actual systems on the specific property — it changes inspections, insurance, and monthly costs.' },
      { q: 'How is Springfield different from Eugene for buyers?', a: 'Springfield generally offers more home for the money, a quicker route to the McKenzie corridor, and a more compact, small-city feel. Eugene brings the university, larger job base, and bigger cultural calendar. Many buyers shop both; the right answer depends on commute and lifestyle.' },
      { q: 'What should sellers in Springfield do before listing?', a: 'Tighten the basics: honest pricing against both Springfield and Eugene comps, professional photos, and repairs documented up front. If your property touches rural systems — a well, septic, or outbuildings — gather those records early; they are the first things serious buyers ask about.' },
    ],
  },
  {
    slug: 'thurston',
    name: 'Thurston',
    kicker: 'The gateway neighborhood',
    img: '/assets/img/springfield-river-1.jpg',
    imgAlt: 'River flowing past Clearwater Park in Springfield, Oregon',
    blurb: 'Thurston is east Springfield — the last stoplights, the last big grocery run, and the doorway to the McKenzie river road.',
    hub: [
      `Every trip up the McKenzie starts in Thurston. This east-Springfield district is the corridor's gateway: the final full grocery stop, the gas you top off before heading up river, and the neighborhoods commuters choose when they want the valley close and the city closer.`,
      `Thurston grew as Springfield stretched east, so its housing stock leans newer than the city core — subdivisions, family streets, and properties that back up to the beginnings of open country. Five minutes east on 126 and the road narrows, the trees close in, and the river valley takes over.`,
      `For a lot of my clients, Thurston is the compromise that ends the debate: one spouse wants acreage quiet, the other wants a short drive to everything. Thurston splits the difference and keeps both happy.`,
    ],
    facts: [
      'Easternmost Springfield — the true start of the river road',
      'The corridor’s last major services heading east on Highway 126',
      'Newer housing stock than central Springfield, generally',
      'Minutes from Hendricks Bridge and the lower McKenzie',
    ],
    buying: [
      `Thurston buyers are usually solving for the same equation: maximum access to the river country with minimum sacrifice of convenience. The neighborhood delivers, which keeps demand steady. Come pre-approved and ready to move when the right home appears.`,
      `Pay attention to the transition zone at the eastern edge, where city lots give way to the first rural parcels. Prices, utilities, and lifestyle all shift within a short stretch of road — I will tell you exactly which world each address belongs to.`,
    ],
    selling: [
      `Selling in Thurston means selling position: your buyer wants the McKenzie close and the grocery store closer, and your marketing should say so explicitly. Homes here also draw up-river owners moving toward town, who already know exactly why Thurston works.`,
      `Because much of the housing stock is similar in age, condition separates winners. Small pre-listing investments — paint, lighting, landscape cleanup — return outsized results when buyers are comparing four similar floor plans.`,
    ],
    living: [
      `Life in Thurston runs on easy logistics. Work in Springfield, Eugene, or Gateway; be at Hendricks Bridge boat launch in ten minutes; do your whole week's shopping without crossing town. Weekends tilt naturally up river — the valley starts where your street ends.`,
      `It is a neighborhood of practical routines: school runs, ball fields, garage projects, and the steady stream of drift boats and rafts trailering past on summer mornings, reminding you why you live at the mouth of the valley.`,
    ],
    faqs: [
      { q: 'Where exactly is Thurston?', a: 'Thurston is the eastern district of Springfield, Oregon, along Highway 126 and Thurston Road. It is the last stretch of full city services before the highway follows the McKenzie River east into the valley.' },
      { q: 'Why do McKenzie commuters like Thurston?', a: 'Position. It sits at the very start of the river road, so up-river drives skip crossing Springfield entirely, while groceries, gas, and services stay within a few minutes of home.' },
      { q: 'Is Thurston on city utilities?', a: 'Most of Thurston is on Springfield city water and sewer, but the eastern fringe transitions to rural systems. Verify per property — the line between the two runs through this district.' },
      { q: 'What is the drive from Thurston to the upper valley?', a: 'Roughly: Walterville in about ten minutes, Leaburg around twenty, Vida about thirty, Blue River forty-five, and McKenzie Bridge near an hour, depending on season and traffic.' },
    ],
  },
  {
    slug: 'cedar-flat',
    name: 'Cedar Flat',
    kicker: 'First taste of the valley',
    img: '/assets/img/mckenzie-river-1.jpg',
    imgAlt: 'The McKenzie River Valley near the lower corridor',
    blurb: 'Cedar Flat is where the corridor stops feeling like town — the first rural stretch past Thurston, with the river suddenly out the window.',
    hub: [
      `Just past the last Thurston stoplight, the valley starts working on you. Cedar Flat is the corridor's first true rural stretch — small acreages, garden ground, and homes tucked between Highway 126 and the hills, with the McKenzie beginning to show itself through the trees.`,
      `This is transition country in the best sense. You are close enough to Springfield that a forgotten grocery item is a fifteen-minute round trip, yet the properties live rural: wells, septic systems, shops and outbuildings, room for animals and projects.`,
      `Cedar Flat rarely gets the headlines that Vida's covered bridge or Blue River's lakes get, and residents like it that way. It is the quiet, practical way to own a piece of the valley without giving up town.`,
    ],
    facts: [
      'First rural stretch of the corridor east of Springfield/Thurston',
      'Small-acreage properties: wells, septic, shops and outbuildings',
      'Fifteen-ish minutes to full Springfield services',
      'Camp Creek Road connects toward the Mohawk Valley side',
    ],
    buying: [
      `Cedar Flat is often where buyers first confront rural systems: your inspection list grows to include well flow and water quality, septic condition, and outbuilding wiring. None of it should scare you — it just needs to be checked by people who know what right looks like out here.`,
      `Because the area mixes parcel sizes and property styles, comps take local judgment. Two neighboring properties can differ by an outbuilding, an irrigation setup, or usable acreage in ways a city appraisal lens misses.`,
    ],
    selling: [
      `Sellers here have a great story: real rural living at the shortest possible distance from town. Buyers priced out of close-in acreage anywhere in Lane County look here first — your marketing should lead with the systems and the setup, not just the house.`,
      `Get your records file together before listing: well log, septic pumping history, any permits for shops or additions. Cedar Flat buyers tend to be practical people; a ready file reads as a well-kept property.`,
    ],
    living: [
      `Living in Cedar Flat means rural rhythms with a town safety net. Firewood in the fall, garden beds in the spring, and the river minutes away all summer — with commutes that stay reasonable to Springfield, Gateway, or Eugene.`,
      `Neighbors know each other here. It is the kind of stretch where tractors get borrowed, extra zucchini gets left on porches, and the wave off the steering wheel is standard equipment.`,
    ],
    faqs: [
      { q: 'Where is Cedar Flat on the corridor?', a: 'Cedar Flat is the first rural area east of Springfield’s Thurston district on Highway 126, before you reach Walterville. It marks the start of well-and-septic country on the McKenzie river road.' },
      { q: 'Are Cedar Flat properties on wells and septic?', a: 'Generally yes — most properties here run private wells and septic systems. Budget for well flow and water quality testing plus a septic inspection in any purchase.' },
      { q: 'How far is Cedar Flat from shopping and services?', a: 'Roughly ten to fifteen minutes to full services in Thurston and Springfield — close enough that many residents barely notice they have left town, which is exactly the appeal.' },
      { q: 'Is Cedar Flat a good fit for hobby farms?', a: 'Many properties suit gardens, small livestock, and shop projects. Confirm zoning and any land-use rules for the specific parcel before you plan — allowed uses vary by zone.' },
    ],
  },
  {
    slug: 'walterville',
    name: 'Walterville',
    kicker: 'First stop up the river road',
    img: '/assets/img/mckenzie-valley-3.jpg',
    imgAlt: 'Flat water on the lower McKenzie near Walterville, Oregon',
    blurb: 'Walterville is the lower valley’s hub — a real community with the river out back and town ten minutes down the road.',
    hub: [
      `Walterville is where the corridor becomes a community. The lower valley's little hub has its own store, its own school-and-grange rhythm of country life, and some of the most livable river country anywhere on the McKenzie: flat water, big cottonwoods, and pastures running toward the hills.`,
      `The river defines the place. Hendricks Bridge Park puts a launch and day-use water right at the neighborhood's doorstep, and the historic Walterville canal — part of the valley's century-old hydropower story — threads through the landscape as a reminder that people have been putting this river to work for generations.`,
      `Ten minutes from Thurston, Walterville asks almost no sacrifice for its quiet. That balance keeps demand steady for everything from cottages to full farm setups.`,
    ],
    facts: [
      'The lower valley’s community hub, about ten minutes east of Springfield',
      'Hendricks Bridge Park: boat launch and day-use on the lower McKenzie',
      'Historic Walterville canal, part of the valley’s early hydropower era',
      'Golf on the river: the McKenzie River Golf Course sits in this stretch',
      'Mix of riverfront, pasture, and small-acreage properties',
    ],
    buying: [
      `Walterville buying is about micro-position: river frontage versus river access, canal-side versus pasture, highway-close versus tucked-away. Each carries different flood mapping, insurance, and lifestyle math — I walk every one of those angles with you before you write.`,
      `Inventory is finite and local demand is real, so preparation wins. Have your financing set, your inspection team ready for wells and septic, and your decision framework clear before the right property appears.`,
    ],
    selling: [
      `Selling in Walterville, lead with the lifestyle: launch-your-boat proximity, valley views, and a ten-minute town run. Buyers from Springfield and Eugene are actively hunting for exactly this, and buyers relocating from farther away find it reads like a postcard.`,
      `Riverfront and near-water properties deserve extra care in preparation — clear the water view, document the bank, and assemble flood and insurance facts before questions come. Confidence sells river property.`,
    ],
    living: [
      `Life in Walterville follows the river's calendar: spring fishing, summer evenings on the water at Hendricks Bridge, fall colors down the whole valley, and quiet winters when the river runs high and loud. The community is small enough to know you and big enough to function.`,
      `Practical life stays easy — Thurston's services are ten minutes west, and the commute to Springfield, Gateway, or Eugene is entirely reasonable. It is the rare address where "convenient" and "on the river" are both true.`,
    ],
    faqs: [
      { q: 'How far is Walterville from Springfield?', a: 'About ten minutes east on Highway 126 from the Thurston district — close enough for easy commutes and errands, far enough that the valley has fully taken over the scenery.' },
      { q: 'Where do people access the river in Walterville?', a: 'Hendricks Bridge Park is the local landmark access — a launch and day-use park on the lower McKenzie. Many properties also enjoy private frontage; access rights vary by parcel, so verify specifics.' },
      { q: 'What is the Walterville canal?', a: 'A historic hydropower canal that has been part of the lower valley for over a century. Some properties border it; ownership, easements, and setback details vary, so we confirm them during due diligence.' },
      { q: 'Does Walterville flood?', a: 'Parts of the lower valley floor carry mapped flood zones, and many properties sit safely outside them. Every river-country purchase here should start with the FEMA map, an insurance quote, and the property’s elevation story.' },
    ],
  },
  {
    slug: 'deerhorn',
    name: 'Deerhorn',
    kicker: 'Quiet lanes, golf on the river',
    img: '/assets/img/mckenzie-bridge-1.jpg',
    imgAlt: 'Clear water of the McKenzie River along a wooded bank',
    blurb: 'Deerhorn is the corridor’s hidden pocket — a lattice of quiet lanes between Walterville and Leaburg where the river slows and so do you.',
    hub: [
      `Cross the river at Deerhorn Road and you enter one of the corridor's best-kept pockets. Deerhorn runs along the McKenzie's south bank in a web of quiet lanes — no through-traffic, no commercial strip, just river properties, meadows, and the kind of stillness the highway side rarely offers.`,
      `The area's calling cards are water and pace. The river braids gently through this stretch, golfers work the riverside fairways of the local course, and herons outnumber commuters most mornings.`,
      `Because Deerhorn sits off the highway, its properties trade on privacy. When one comes available, buyers who know the corridor pay attention — quiet, close-in river country is the scarcest thing on the McKenzie.`,
    ],
    facts: [
      'South-bank pocket between Walterville and Leaburg, off the highway',
      'Quiet dead-end lanes rather than through-roads',
      'Riverside golf in the Deerhorn/Walterville stretch',
      'Roughly fifteen minutes to Springfield services',
    ],
    buying: [
      `Deerhorn purchases are patience purchases: inventory is thin, and the best properties often sell to buyers who were ready before they listed. Tell me what you want here and I will keep my ears open — quiet-market awareness matters more in Deerhorn than anywhere on the lower river.`,
      `Being off-highway, access details deserve care: bridge and road maintenance, easements on shared lanes, and winter condition of your specific route. It is all manageable; it just belongs in your diligence.`,
    ],
    selling: [
      `Scarcity is your friend. Deerhorn properties rarely list, so when yours does, positioning it as the rare off-highway river address it is — with photography that captures the quiet — draws serious, qualified attention fast.`,
      `Because buyers here are often corridor-savvy, they will ask sharp questions about the bank, the systems, and the access. A complete records file lets your property answer with confidence.`,
    ],
    living: [
      `Deerhorn living is measured in river sounds and morning light. You are fifteen minutes from a full grocery store and a world away from traffic; the lanes invite evening walks, and the river invites everything else.`,
      `Neighbors are few and known. Life organizes around the seasons — fishing’s rhythm, the garden, firewood — with town runs slotted in when convenient rather than constant.`,
    ],
    faqs: [
      { q: 'Where is Deerhorn?', a: 'Deerhorn is the south-bank area of the lower McKenzie between Walterville and Leaburg, reached via Deerhorn Road. It is a residential pocket of quiet lanes rather than a highway-side community.' },
      { q: 'Why is Deerhorn considered special on the corridor?', a: 'It combines close-in location with off-highway quiet — a rare pairing. River properties here feel remote while staying about fifteen minutes from Springfield services.' },
      { q: 'Is there golf in Deerhorn?', a: 'Yes — the riverside course in the Deerhorn/Walterville stretch is a fixture of the lower valley, and some properties enjoy fairway or near-course settings.' },
      { q: 'How often do Deerhorn properties come up for sale?', a: 'Infrequently — inventory is limited and owners stay. Serious buyers benefit from being pre-approved and letting me watch the area on their behalf.' },
    ],
  },
  {
    slug: 'leaburg',
    name: 'Leaburg',
    kicker: 'Flat water country',
    img: '/assets/img/leaburg-2.jpg',
    imgAlt: 'Calm water of Leaburg Lake reflecting the surrounding forest',
    blurb: 'Leaburg is the corridor’s flat-water heart — lake mornings, a century of river history, and some of the prettiest home water on the McKenzie.',
    hub: [
      `Leaburg gathers the McKenzie into stillness. The dam here — part of the river's story for nearly a century — creates Leaburg Lake's glassy mornings, and the community around it enjoys some of the most beautiful home water in the valley: broad, calm, and framed in Douglas fir.`,
      `This stretch has long been a fishing and river-culture hub. Drift boats work the water below the dam, herons stalk the margins, and the fish hatchery is part of local life. Homes range from classic river cabins to full-scale riverfront residences and small acreages back from the water.`,
      `At roughly twenty minutes from Springfield, Leaburg hits a sweet spot: genuinely up river, still workable for daily life. It is many buyers' mental picture of "living on the McKenzie."`,
    ],
    facts: [
      'Leaburg Dam and Lake — flat water and nearly a century of river history',
      'Long-standing fishing culture; hatchery is part of local life',
      'Roughly twenty minutes east of Springfield on Highway 126',
      'Mix of riverfront homes, cabins, and small acreage',
    ],
    buying: [
      `Leaburg buying rewards water literacy: lake-front versus moving-water frontage, dam influence on levels, and bank character all shape both lifestyle and diligence. I will walk the waterline with you and translate what you are looking at.`,
      `Cabins and older river homes here can carry charming quirks — aged systems, additions, wood heat. Budget inspection attention accordingly; the right property is worth it, and the wrong surprises are avoidable.`,
    ],
    selling: [
      `Flat water photographs like a dream — use that. Leaburg listings deserve golden-hour photography and marketing that leads with the water lifestyle, because that is precisely what your buyer is purchasing.`,
      `Expect educated buyers who ask about levels, flood mapping, and the bank. We will assemble that story in advance so your listing answers questions instead of raising them.`,
    ],
    living: [
      `Life in Leaburg is organized around the water: coffee watching the lake steam, evening casts below the dam, and the seasonal pageant of the valley running past your window. It is quieter than the lower valley and more connected than the upper.`,
      `Services are a planned-trip rhythm — Springfield twenty minutes west — and locals wouldn't trade the trade-off. This is the corridor at its most classically "river life."`,
    ],
    faqs: [
      { q: 'What creates Leaburg Lake?', a: 'Leaburg Dam, a hydropower-era structure that has shaped this stretch of the McKenzie for close to a century, backs up the river into the calm reach known as Leaburg Lake.' },
      { q: 'Is Leaburg good for fishing?', a: 'The Leaburg stretch is storied fly and drift water, with a long-standing local fishing culture and hatchery presence. Regulations vary by reach and season — always check current Oregon rules.' },
      { q: 'How far is Leaburg from town?', a: 'About twenty minutes to Thurston/Springfield services along Highway 126 — a workable daily commute and an easy errand run.' },
      { q: 'What property types exist in Leaburg?', a: 'A broad mix: classic river cabins, updated riverfront homes, and small acreages off the water. Systems (wells, septic, wood heat) and bank character vary widely, so per-property diligence matters.' },
    ],
  },
  {
    slug: 'vida',
    name: 'Vida',
    kicker: 'The postcard of the corridor',
    img: '/assets/img/goodpasture-bridge-1.jpg',
    imgAlt: 'The white Goodpasture covered bridge spanning the McKenzie River at Vida',
    blurb: 'Vida is the valley’s postcard — home of the Goodpasture covered bridge and classic mid-corridor river living.',
    hub: [
      `Vida owns the corridor's most famous view. The Goodpasture covered bridge — white, wooden, and photographed constantly since 1938 — crosses the McKenzie here, and everything about the community lives up to the postcard: emerald water, timbered hills, and river properties people dream about.`,
      `The 2020 fire touched parts of this stretch, and Vida's story since has been one of rebuilding with grit — newer construction now stands alongside classic cabins, and the community's spirit is stronger than ever.`,
      `Mid-corridor position gives Vida a balanced life: about half an hour to Springfield, with the upper valley's recreation — reservoirs, hot springs, trail country — just up the road.`,
    ],
    facts: [
      'Goodpasture covered bridge (1938) — among Oregon’s most photographed',
      'Classic mid-corridor river community, roughly 30 minutes from Springfield',
      'Mix of longtime cabins and newer post-2020 construction',
      'Gateway position between the lower valley and the upper river',
    ],
    buying: [
      `Vida offers both heritage properties and newer builds, which means due diligence runs the full spectrum — vintage cabin systems on one property, modern engineered construction on the next. Each has advantages; I will help you weigh them honestly.`,
      `On fire-affected parcels, we look carefully at what was rebuilt, replanted, and permitted. There are excellent opportunities in this stretch for buyers who evaluate with clear eyes and good information.`,
    ],
    selling: [
      `Selling in Vida means selling an icon's neighborhood. Your marketing gets to borrow the bridge's fame — buyers already carry a mental image of this stretch, and your listing should confirm it with photography worthy of the setting.`,
      `Newer construction sells on documentation: permits, warranties, and build specs. Heritage properties sell on character plus honesty about systems. Either way, the records file does heavy lifting.`,
    ],
    living: [
      `Living in Vida means the postcard is your commute. The bridge, the emerald water, the canyon light — daily life happens inside scenery other people drive hours to photograph.`,
      `The community is tight-knit and proud, shaped by both long roots and the shared work of rebuilding. Neighbors show up for each other here in ways that surprise newcomers from town.`,
    ],
    faqs: [
      { q: 'What is the Goodpasture Bridge?', a: 'A 1938 white covered bridge spanning the McKenzie at Vida — one of Oregon’s longest and most photographed covered bridges, and the enduring symbol of the corridor.' },
      { q: 'How far is Vida from Springfield and Eugene?', a: 'Roughly thirty minutes to Springfield services on Highway 126, and about forty to central Eugene, depending on season and traffic.' },
      { q: 'How did the 2020 fire affect Vida?', a: 'Parts of the Vida–Blue River stretch were affected, and the years since have brought significant rebuilding — newer homes now mix with the valley’s classic cabins. Property-specific history is part of normal due diligence here, handled respectfully and factually.' },
      { q: 'Is Vida riverfront expensive?', a: 'River frontage anywhere on the McKenzie carries a premium, and iconic mid-corridor stretches like Vida hold value well. Exact pricing depends on frontage, bank, systems, and improvements — I price by walking the property, not by algorithm.' },
    ],
  },
  {
    slug: 'nimrod',
    name: 'Nimrod',
    kicker: 'Mid-corridor quiet',
    img: '/assets/img/mckenzie-river-3.jpg',
    imgAlt: 'Turquoise current of the McKenzie River in mid-corridor forest',
    blurb: 'Nimrod is the McKenzie at its most unhurried — a mid-valley stretch of launches, meadows, and river houses with room to breathe.',
    hub: [
      `Between Vida and Finn Rock, the valley exhales. Nimrod is a name on the river more than a town — a scatter of properties along a gorgeous mid-corridor reach where boat launches outnumber businesses and the loudest thing most days is the current.`,
      `This stretch is beloved by drift boaters and anglers, who know its water intimately. Properties here trade on elbow room: bigger parcels, longer river frontages, and the sense of having your own piece of the valley rather than an address in it.`,
      `Nimrod suits people done with neighbors-through-the-wall living. It asks a longer town run and returns genuine river-country privacy.`,
    ],
    facts: [
      'Quiet mid-corridor reach between Vida and Finn Rock',
      'Favorite water for drift boats and fly anglers',
      'Larger parcels and longer frontages than the lower valley',
      'Roughly 35–40 minutes from Springfield services',
    ],
    buying: [
      `Nimrod purchases are land purchases as much as home purchases: frontage character, meadow versus timber, and access all drive value. Expect wells, septic, and often wood heat — the full rural checklist, which I will quarterback with you.`,
      `Because "Nimrod" covers a loose stretch rather than a defined town, comps require river sense. Two properties with equal acreage can differ enormously by their water. I price this reach on foot, not from a desk.`,
    ],
    selling: [
      `Your buyer is likely a river person already — an angler, a boater, a valley regular who has floated past your bank and wondered. Marketing that speaks fluent river (the water, the launch distance, the fishing) reaches them directly.`,
      `Space is your headline: photograph the frontage, the meadow, the big sky. Nimrod sells the feeling of room, and listings that capture it draw buyers from far beyond Lane County.`,
    ],
    living: [
      `Nimrod living is the deep-breath version of the corridor: mornings measured by river level, evenings by canyon light, town trips consolidated and un-missed. Neighbors are distant but dependable — the upper-valley rule.`,
      `You will learn the water like a local fast: which riffles hold fish, when the spring flows settle, where the herons nest. The river becomes less scenery and more companion.`,
    ],
    faqs: [
      { q: 'Is Nimrod an actual town?', a: 'It is a named locality along the McKenzie rather than an incorporated town — a stretch of river properties and launches between Vida and Finn Rock with a post-office history and a strong identity among river people.' },
      { q: 'What draws buyers to Nimrod?', a: 'Privacy and water. The reach offers larger parcels, quieter frontage, and classic drift-boat water, all within about forty minutes of Springfield.' },
      { q: 'What utilities serve Nimrod properties?', a: 'Private wells and septic are standard; power is available along the corridor, and connectivity varies by address — verify at the driveway. Wood heat is common and beloved.' },
      { q: 'How is fishing on this stretch?', a: 'The mid-corridor is celebrated drift-boat and fly water in the McKenzie tradition. Seasons and rules change, so check current Oregon regulations before you fish.' },
    ],
  },
  {
    slug: 'finn-rock',
    name: 'Finn Rock',
    kicker: 'Landmark on the river',
    img: '/assets/img/mckenzie-fall-1.jpg',
    imgAlt: 'Autumn colors along the McKenzie River near Finn Rock',
    blurb: 'Finn Rock is a river landmark and a tiny community — launches, timber history, and the upper-middle valley’s unhurried pace.',
    hub: [
      `Finn Rock takes its name from the midstream monolith that boaters have steered around for generations, and the tiny community around it keeps the valley's timber-era memory alive. This is the upper-middle corridor: fewer neighbors, taller forest, and a river that feels increasingly wild.`,
      `The Finn Rock launch is one of the most-used put-ins on the McKenzie, and conserved lands in this reach protect floodplain forest — meaning the stretch's character has guardians and its beauty has a future.`,
      `Homes and parcels here suit committed river people: the town run is real (forty-plus minutes), and the reward is living inside one of the corridor's most storied reaches.`,
    ],
    facts: [
      'Named for the landmark rock in the river; historic timber-country stretch',
      'Popular Finn Rock boat launch for drift and raft trips',
      'Conserved floodplain lands protect this reach’s character',
      '40+ minutes to Springfield; Blue River services nearer',
    ],
    buying: [
      `Buying near Finn Rock is buying into the river's culture — expect properties with history, wood heat, and systems that reward careful inspection. Conservation neighbors can be the best kind: quiet, permanent, and green.`,
      `Check the practical layer thoroughly: winter access, power reliability, connectivity at the driveway, and fire-history context for the specific parcel. I will help you build the complete picture before you commit.`,
    ],
    selling: [
      `Finn Rock properties carry name recognition among river people everywhere — use it. Your listing should lead with the reach: the launch, the water, the landmark. Buyers for this stretch often come from beyond the county, already in love with the river.`,
      `Authenticity sells here. Document the property's story — the systems, the improvements, the relationship to the water — and let honest character do the persuading.`,
    ],
    living: [
      `Life at Finn Rock runs on river time. Summer brings the daily flotilla past your bank; fall turns the corridor gold; winter belongs to woodsmoke and high water. You will know your launch neighbors and wave at half the boats by name.`,
      `Provisioning is a rhythm: Blue River for basics up the road, Springfield for the big run. Most residents consolidate trips and treasure the distance — it is the moat around the quiet.`,
    ],
    faqs: [
      { q: 'What is Finn Rock?', a: 'Both a landmark rock in the McKenzie and the small community around it, in the upper-middle corridor between Nimrod and Blue River. The Finn Rock launch is a well-known put-in for river trips.' },
      { q: 'How remote is Finn Rock?', a: 'Expect forty-plus minutes to full Springfield services, with closer basics toward Blue River. It is genuinely up river — the appeal and the logistics both flow from that.' },
      { q: 'What does conservation land nearby mean for owners?', a: 'Portions of this reach’s floodplain are conserved, which protects the stretch’s natural character. For neighboring owners it generally means stable, undeveloped surroundings; specific implications vary by parcel.' },
      { q: 'Are properties here on wells and septic?', a: 'Yes, as throughout the upper corridor — private wells and septic systems are standard, and their condition drives value. Full rural diligence applies.' },
    ],
  },
  {
    slug: 'blue-river',
    name: 'Blue River',
    kicker: 'Two lakes, one comeback',
    img: '/assets/img/blue-river-2.jpg',
    imgAlt: 'The clear waters of Blue River, Oregon',
    blurb: 'Blue River is the upper valley’s hub — reservoir summers, trailhead winters, and a community rebuilding with famous grit.',
    hub: [
      `Blue River anchors the upper McKenzie. The community sits where its namesake river meets the McKenzie, with two celebrated reservoirs — Blue River Lake and Cougar — supplying the summers, and Tokatee's renowned golf course, hot-springs country, and endless trail systems filling every other season.`,
      `The 2020 Holiday Farm Fire hit Blue River hard, and what has happened since is the valley's proudest story: a community that chose to rebuild, and is doing it with energy — new construction, restored services, and an unbroken identity.`,
      `For buyers, Blue River offers the upper valley's widest range: rebuilt homes, legacy cabins that came through, buildable land, and recreation at a density few places in Oregon match.`,
    ],
    facts: [
      'Upper-valley hub where Blue River meets the McKenzie',
      'Blue River Reservoir and Cougar Reservoir recreation',
      'Tokatee Golf Club — one of Oregon’s celebrated courses',
      'Rebuilding community following the 2020 fire — significant newer construction',
      'About 45 minutes east of Springfield',
    ],
    buying: [
      `Blue River requires fluency in post-fire due diligence: what burned, what was rebuilt to modern code, how the landscape is recovering parcel by parcel. Newer construction here can be an outstanding buy — modern systems in a classic setting — when evaluated with full information.`,
      `Recreation access is a genuine value driver: proximity to the reservoirs, Tokatee, and trailheads differentiates otherwise similar properties. Know what your lifestyle needs, and buy position accordingly.`,
    ],
    selling: [
      `Selling in Blue River means telling the comeback story with confidence: modern rebuilt homes with warranties and code-current systems are rare in river country, and buyers increasingly seek exactly that combination.`,
      `Lead marketing with the recreation map — lakes, golf, trails, hot springs — because your buyer is buying a basecamp. Document everything about the build; transparency converts.`,
    ],
    living: [
      `Living in Blue River is living at the center of the upper valley's playground: reservoir mornings, golf afternoons, trail evenings, and a community whose shared rebuilding has forged uncommon bonds.`,
      `Services have been steadily returning, with Springfield's full array about forty-five minutes down-valley. Residents plan, provision, and would not trade the trailhead life for convenience.`,
    ],
    faqs: [
      { q: 'What recreation defines Blue River?', a: 'Two reservoirs (Blue River Lake and Cougar), Tokatee Golf Club, hot-springs country up the Aufderheide corridor, and trail systems in every direction — one of Oregon’s densest recreation clusters.' },
      { q: 'How has Blue River recovered since 2020?', a: 'Through determined rebuilding: new homes built to modern code, restored community services, and a landscape recovering season by season. Due diligence on any parcel includes its specific fire-and-rebuild history, handled factually.' },
      { q: 'Is newer construction common in Blue River now?', a: 'Yes — the rebuild years have produced a meaningful stock of recent construction, unusual for river country and attractive for buyers wanting modern systems in a valley setting.' },
      { q: 'How far is Blue River from town?', a: 'Roughly forty-five minutes to Springfield on Highway 126. Locals consolidate town runs and lean on upper-valley basics between trips.' },
    ],
  },
  {
    slug: 'rainbow',
    name: 'Rainbow',
    kicker: 'Old growth neighbors',
    img: '/assets/img/rainbow-or-1.jpg',
    imgAlt: 'Old-growth forest canopy near Rainbow in the McKenzie Valley',
    blurb: 'Rainbow is the upper valley’s forest community — big trees, river confluences, and cabins tucked into the green.',
    hub: [
      `Rainbow hides in the trees across the river from Blue River, where the forest turns serious. Old growth stands at Delta shade the river's braids, the Aufderheide scenic byway begins its climb toward Cougar country, and the community's homes tuck into green so deep it changes the light.`,
      `This is classic upper-valley cabin country — properties passed down, properties reimagined, and a few parcels that still feel like secrets. The McKenzie and its tributaries braid generously through this reach, and river song is the neighborhood soundtrack.`,
      `Rainbow residents are here for the forest first: the trailheads, the shade, the scale of the trees. Everything else is logistics, happily managed.`,
    ],
    facts: [
      'Forest community across from Blue River, near the Aufderheide byway',
      'Old-growth groves at Delta shade this reach of the river',
      'Classic cabin country with braided river channels',
      'Gateway to Cougar Reservoir and hot-springs country',
    ],
    buying: [
      `Rainbow properties demand forest-specific diligence: big-tree proximity (beauty and responsibility), shade patterns for solar and gardens, and defensible-space planning. The reward is living inside cathedral forest minutes from world-class recreation.`,
      `Access lanes here are intimate — verify easements, maintenance arrangements, and winter character. I will help you love the property and understand the practicalities in equal measure.`,
    ],
    selling: [
      `Sell the forest. Rainbow's buyer wants exactly what your property has — big trees, river sound, trailhead life — and photography in the green light of this reach does half the persuasion.`,
      `Document your property's forest stewardship: tree health, defensible space, any thinning or arborist history. Sophisticated buyers read good stewardship as protected value.`,
    ],
    living: [
      `Life in Rainbow happens under canopy: filtered summer light, moss winters, and the constant company of moving water. The Aufderheide is your scenic driveway to lakes and hot springs; Blue River supplies the basics across the bridge.`,
      `It is quiet in a way that recalibrates people. After a season, town noise feels like the anomaly and the forest feels like the baseline — which is precisely why residents stay.`,
    ],
    faqs: [
      { q: 'Where is Rainbow, Oregon?', a: 'Rainbow sits across the McKenzie from Blue River in the upper valley, near the start of the Aufderheide scenic byway toward Cougar Reservoir. It is a small forest community rather than a commercial center.' },
      { q: 'What is special about the forest here?', a: 'The reach includes celebrated old-growth groves — notably around Delta — with big Douglas firs and cedars shading braided river channels. Living here means genuine big-tree country.' },
      { q: 'What should buyers check on forested parcels?', a: 'Tree health and hazard assessment, defensible-space potential, shade and solar patterns, access easements, and standard rural systems. Forest living is wonderful and specific — diligence should be too.' },
      { q: 'How do residents handle services?', a: 'Basics via Blue River across the river, full services in Springfield about forty-five minutes down-valley, and the upper-valley habit of consolidated town runs.' },
    ],
  },
  {
    slug: 'mckenzie-bridge',
    name: 'McKenzie Bridge',
    kicker: 'Last stop before the pass',
    img: '/assets/img/sahalie-falls-1.jpg',
    imgAlt: 'Sahalie Falls thundering through moss and old growth near McKenzie Bridge',
    blurb: 'McKenzie Bridge is the top of the valley — hot springs country, waterfall trails, and forest-edge living at the corridor’s summit end.',
    hub: [
      `McKenzie Bridge is where the valley meets the high Cascades. The corridor's uppermost community sits in deep forest at the doorstep of everything the McKenzie is famous for: Sahalie and Koosah Falls minutes up the highway, the Blue Pool's impossible turquoise, hot springs in two directions, and the McKenzie River Trail threading through it all.`,
      `Life here is forest-edge in the fullest sense — resort-country history, ranger-district presence, and homes that serve as basecamps for the best recreation in Oregon. Above town, the highway climbs toward Clear Lake (the river's crystalline headwaters) and the passes beyond.`,
      `Owning at McKenzie Bridge means committing to the upper valley: real distances, real seasons, and the daily reward of living where others vacation.`,
    ],
    facts: [
      'Uppermost corridor community, at the edge of the high Cascades',
      'Minutes from Sahalie & Koosah Falls and the Tamolitch Blue Pool',
      'Hot springs country: Belknap on the highway, Terwilliger up the Aufderheide',
      'McKenzie River National Recreation Trail — 26 celebrated miles',
      'Clear Lake headwaters and the passes just above',
    ],
    buying: [
      `Buying at McKenzie Bridge is buying a basecamp: evaluate properties by their four-season function — winter access, wood heat, storage for the toys, generator readiness — as much as their summer charm.`,
      `Cabins here span a century of styles and systems. I will help you distinguish charming-and-sound from charming-and-project, and price the difference honestly.`,
    ],
    selling: [
      `Your listing's competition is not the house down the road; it is the buyer's daydream. Feed it: falls, trail, hot springs, river — marketed vividly and accurately, with the practical excellence (systems, access, storage) documented alongside.`,
      `Vacation-minded buyers shop from everywhere. Broad-reach marketing plus airtight remote-showing logistics extends your buyer pool far beyond the valley.`,
    ],
    living: [
      `McKenzie Bridge living is seasonal immersion: waterfall springs, river summers, larch-gold falls, and snow-line winters with the woodstove ticking. The trail is your gym, the springs your spa, the river your calendar.`,
      `Community is small, capable, and shows up for each other — the upper-valley covenant. Provisioning is planned, connectivity is address-specific, and the trade is one residents re-choose daily.`,
    ],
    faqs: [
      { q: 'What recreation is closest to McKenzie Bridge?', a: 'A remarkable density: Sahalie and Koosah Falls, the Tamolitch Blue Pool, Belknap and Terwilliger hot springs, the 26-mile McKenzie River Trail, and Clear Lake at the headwaters — all within a short drive.' },
      { q: 'How far is McKenzie Bridge from Springfield?', a: 'Roughly an hour along Highway 126, seasonally variable. Most residents treat town runs as planned provisioning trips.' },
      { q: 'Is winter access difficult?', a: 'The highway is maintained, but elevation and weather demand winter readiness: appropriate vehicles, wood heat or backup power, and driveway planning. It is very livable with the right setup.' },
      { q: 'Do properties here work as vacation homes?', a: 'Many serve exactly that role. If rental use matters to you, verify current county rules and any specific restrictions for the property — regulations evolve, so we confirm rather than assume.' },
    ],
  },
  {
    slug: 'eugene',
    name: 'Eugene',
    kicker: 'The metro anchor',
    img: '/assets/img/eugene-house-1.jpg',
    imgAlt: 'A classic Eugene, Oregon neighborhood home',
    blurb: 'Eugene is the metro anchor a short drive from the corridor — the university city many valley buyers commute to, and many sellers’ buyers come from.',
    hub: [
      `Eugene is the corridor's big neighbor: the University of Oregon's city, the metro's cultural engine, and the place a large share of valley residents drive to for work, sports, and Saturday markets. For McKenzie-minded buyers, Eugene is context — the option you weigh river life against, and the market your future buyer may come from.`,
      `I serve Eugene primarily as the corridor's on-ramp: helping Eugene households find their river place, and helping valley sellers market into Eugene's deep buyer pool. When a Eugene purchase or sale connects to that journey, I am glad to help directly.`,
      `The city's neighborhoods span classic tree-lined districts to south-hills view homes — and every one of them is forty-five minutes from a drift boat launch, which is the whole point of this valley.`,
    ],
    facts: [
      'University of Oregon and the metro’s cultural core',
      'Roughly 20 minutes from the corridor’s start at Thurston',
      'The deepest buyer pool for valley sellers',
      'Track-town identity, market days, and river-path city life',
    ],
    buying: [
      `If you are Eugene-based and river-dreaming, your buying power up the corridor is often stronger than you expect — I will map what Springfield-to-summit options your budget commands, and we will weigh commute, systems, and lifestyle with real numbers.`,
      `Buying in Eugene itself? I work it selectively, and I will always tell you honestly when a dedicated in-town specialist or my team's Eugene bench serves you better. The advice stays straight either way.`,
    ],
    selling: [
      `Valley sellers: Eugene is where a large share of your buyers live today. My marketing pushes corridor listings into Eugene's feeds, networks, and imaginations deliberately — the dream of river life is strongest among those closest to it.`,
      `Eugene homeowners heading up river: coordinating a city sale with a valley purchase is my daily work. We sequence, negotiate, and time both sides so you move once, calmly.`,
    ],
    living: [
      `Eugene living brings the full metro kit — restaurants, Ducks game days, the market, trails along the Willamette — with the corridor as your weekend backyard. Many households live this hybrid happily for years before the river finally wins.`,
      `When it wins, I am the call: the agent who knows both the city you are leaving and every mile of the valley you are headed to.`,
    ],
    faqs: [
      { q: 'Does George work in Eugene?', a: 'Selectively — my specialty is the McKenzie corridor from Springfield to McKenzie Bridge. I help Eugene households buy up river, valley sellers market to Eugene buyers, and handle connected Eugene transactions directly or alongside my Operative Group teammates.' },
      { q: 'How far is Eugene from the McKenzie Valley?', a: 'About twenty minutes to the corridor’s start at Thurston/Springfield, forty to Leaburg–Vida water, and roughly an hour and change to McKenzie Bridge.' },
      { q: 'Why does Eugene matter to valley sellers?', a: 'Depth of demand. The metro holds the largest concentration of buyers dreaming about river property — smart valley marketing targets Eugene deliberately.' },
      { q: 'Can I keep a Eugene job and live up river?', a: 'Thousands do. Lower-corridor addresses (Cedar Flat through Leaburg) keep commutes very manageable; mid-corridor works for flexible schedules; upper valley suits remote and semi-retired life. We will match the mile to your Monday.' },
    ],
  },
  {
    slug: 'camp-creek',
    name: 'Camp Creek',
    kicker: 'The quiet side valley',
    img: '/assets/img/willamette-valley-1.jpg',
    imgAlt: 'Farmland and forested hills in a Willamette Valley side valley',
    blurb: 'Camp Creek is the corridor’s pastoral side pocket — barn-and-pasture country folded into the hills between the McKenzie and the Mohawk.',
    hub: [
      `Camp Creek Road leaves the river near Cedar Flat and climbs into a different postcard: a pastoral side valley of pastures, barns, and timbered ridgelines, running the quiet miles between the McKenzie corridor and the Mohawk Valley.`,
      `This is small-farm country close to town — horse setups, hay ground, family compounds, and homesteads that have fed generations. The river is minutes away, Springfield barely farther, yet the valley keeps a horse-and-gravel hush the highway never hears.`,
      `Buyers wanting land-first properties — where the acreage is the point and the house serves it — find Camp Creek delivers the most pasture per commute-minute on this side of the county.`,
    ],
    facts: [
      'Pastoral side valley connecting the McKenzie corridor toward the Mohawk',
      'Small farms, horse properties, and homestead acreage',
      'Minutes from Cedar Flat/Walterville and Springfield services',
      'Gravel-quiet roads and working-land character',
    ],
    buying: [
      `Camp Creek diligence is land diligence: water for stock and irrigation, fencing and cross-fencing, soils and drainage, barn condition, and the zoning that governs what your plans require. I will help you evaluate the dirt as rigorously as the house.`,
      `Properties here vary enormously in usable acreage versus raw acreage. We will walk fence lines, not just floor plans, before you commit.`,
    ],
    selling: [
      `Sell the setup: fencing, water, outbuildings, and the life your land makes possible. Camp Creek buyers are shopping for capability — a listing that documents infrastructure sells against prettier-but-impractical competition.`,
      `Your buyer pool spans horse people, homesteaders, and town families ready for land. Marketing that shows the property working — animals grazing, hay cut, garden producing — converts dreamers into offers.`,
    ],
    living: [
      `Camp Creek life runs on chores and seasons — morning feeds, summer hay, woodsmoke falls — with town close enough that none of it requires sacrifice. It is the working-land counterpoint to the corridor’s river romance, and many families blend both.`,
      `The road itself sets the tone: unhurried, neighborly, and lined with places that look loved. People wave here. You will too.`,
    ],
    faqs: [
      { q: 'Where does Camp Creek Road run?', a: 'From the lower McKenzie corridor near Cedar Flat, through its namesake pastoral valley toward the Mohawk Valley — a quiet rural byway minutes from Springfield.' },
      { q: 'What property types define Camp Creek?', a: 'Small farms and acreage: horse properties, hay ground, homesteads, and rural homes with serious outbuildings. Land capability drives value here.' },
      { q: 'What should I verify on a Camp Creek farm property?', a: 'Water (wells, rights, stock water), fencing, soils and drainage, outbuilding condition, and zoning for your intended use — plus the standard rural systems checklist.' },
      { q: 'How close is Camp Creek to services?', a: 'Typically ten to twenty minutes to Springfield/Thurston services depending on how far up the valley you are — remarkably close for genuine farm country.' },
    ],
  },
  {
    slug: 'mohawk-valley',
    name: 'Mohawk Valley',
    kicker: 'The neighboring valley',
    img: '/assets/img/oregon-barn-1.jpg',
    imgAlt: 'A historic barn in rural Lane County, Oregon',
    blurb: 'The Mohawk Valley is the corridor’s sister valley — timber-framed farm country over the hill, with Marcola at its heart.',
    hub: [
      `One ridge north of the McKenzie, the Mohawk Valley runs its own unhurried course. This is timber-and-farm country in the classic Oregon mold — the Mohawk River winding past pastures, the community of Marcola at the valley's heart, and working land traditions that go back generations.`,
      `Many corridor buyers end up comparing the two valleys, and I work both sides of the ridge: the Mohawk offers more pasture and homestead ground for the money, while the McKenzie offers the river itself. Families often split the difference by lifestyle.`,
      `From Marcola, Springfield is a straightforward drive, making the Mohawk one of the area's most livable big-acreage options.`,
    ],
    facts: [
      'The next valley north, following the Mohawk River through Marcola',
      'Timber heritage and multi-generation farm country',
      'Generally more acreage per dollar than riverfront corridors',
      'Straightforward drive to Springfield services',
    ],
    buying: [
      `Mohawk buying favors the land-focused: bigger parcels, working ground, and timber edges. Diligence centers on water, soils, access, and zoning capability — with the same rural-systems rigor as the McKenzie, minus the flood-mapping layer on most parcels.`,
      `If you are torn between valleys, tour both with me in one day. The contrast clarifies most buyers’ priorities within hours.`,
    ],
    selling: [
      `Mohawk sellers reach two audiences: acreage-hunters priced off the river corridor, and legacy-minded buyers drawn to the valley’s farm-and-timber roots. Marketing that documents land capability captures both.`,
      `Cross-list the lifestyle: quiet, capability, and Springfield practicality. I bring McKenzie-corridor buyer traffic to Mohawk listings deliberately — the valleys share one buyer pool.`,
    ],
    living: [
      `Mohawk living is farmland rhythm under timbered ridges: stock to feed, hay to cut, and Marcola’s small-community life binding it together. The river valley next door supplies the waterfalls-and-drift-boats side of life whenever you want it.`,
      `It is quieter than the McKenzie corridor in every season — no highway hum, no tourist summer — which for many residents is the entire argument.`,
    ],
    faqs: [
      { q: 'Where is the Mohawk Valley?', a: 'Immediately north of the McKenzie corridor, following the Mohawk River through Marcola — one ridge and a short drive from Springfield.' },
      { q: 'How does it compare to the McKenzie corridor?', a: 'More farm and timber acreage for the money, without the river-recreation economy. Buyers choose the Mohawk for land capability and deep quiet, the McKenzie for the water itself.' },
      { q: 'Does George cover the Mohawk Valley?', a: 'Yes — my practice covers both valleys, and I regularly tour buyers across the ridge in a single day to compare. One buyer pool, two flavors of country life.' },
      { q: 'What diligence applies to Mohawk properties?', a: 'Full rural checklists: wells and water rights, septic, soils, access easements, timber and zoning considerations. The valley’s working-land character makes land diligence the core of every purchase.' },
    ],
  },
]
